### ISSUE TITLE
publish the library on jcenter

### ISSUE THREAD

**Issue by tomorrowkey** [cookpad/issue-reporter-android#1]

**Comment by hotchemi** [comment]
Hey folks, any update? :eyes:

**Comment by hotchemi** [comment]
Is this issue ready to close?

**Comment by slightair** [comment]
🙊

**Comment by tomorrowkey** [comment]
It is now available on jcenter thanks to @komatatsu https://bintray.com/cookpad-inc/maven/issue-reporter
